name: try

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::921538310930:role/festa-github-actions-role
          aws-region: ap-northeast-1
      - run: aws iam list-roles
